name: update-branches

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RESET_BRANCHES_GITHUB_TOKEN }}

      - name: Run update branches
        id: update-branches
        env:
          CI_TOOL: github
          GITHUB_TOKEN: ${{ secrets.RESET_BRANCHES_GITHUB_TOKEN }}
          UPDATE_BRANCHES: "dev,staging"
        run: script/ci/update-branches.sh
